version: '3'

services:
  scylla-node-1:
    image: scylladb/scylla
    container_name: scylla-node-1

  scylla-node-2:
    image: scylladb/scylla
    container_name: scylla-node-2
    command: --seeds=scylla-node-1
